// Made with tutorial from https://www.digitalocean.com/community/tutorials/how-to-use-winston-to-log-node-js-applications

// Module requirements
const appRoot = require('app-root-path');
const winston = require('winston');
const format = winston.format;

// Define the options for Winston
const options = {
  file: {
    level: 'info',
    filename: `${appRoot}/logs/app.log`,
    handleExceptions: true,
    json: false,
    maxsize: 5242880, // 5MB
    maxFiles: 5,
    colorize: false,
  },
  console: {
    level: 'debug',
    handleExceptions: true,
    json: false,
    colorize: true,
  },
};

// Instantiate new logger
const logger = winston.createLogger({
  format: format.combine(
    format.timestamp(),
    format.printf(info => `${info.timestamp} ${info.level}: ${info.message}`)
  ),
  transports: [
    new winston.transports.File(options.file),
    new winston.transports.Console(options.console)
  ],
  exitOnError: false, // do not exit on handled exceptions
});

// Will retrieve logs generated by morgan and include them in winston generated logs
logger.stream = {
  write: function (message) {
    logger.info(message);
  },
};

module.exports = logger;